# Generated by Django 4.2.7 on 2023-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_gallery',
            },
        ),
        migrations.CreateModel(
            name='PictureChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_chain',
            },
        ),
        migrations.CreateModel(
            name='PictureDroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_droga',
            },
        ),
        migrations.CreateModel(
            name='PictureEma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_ema',
            },
        ),
        migrations.CreateModel(
            name='PicturePhysio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_Physio',
            },
        ),
        migrations.CreateModel(
            name='PictureRwanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_rwanda',
            },
        ),
        migrations.CreateModel(
            name='PictureSom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_som',
            },
        ),
        migrations.CreateModel(
            name='PictureTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture_trust',
            },
        ),
    ]
