# Generated by Django 4.2.7 on 2023-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_remove_picture_picture_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=0.0002013877446403398, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
