# Generated by Django 4.2.7 on 2023-12-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(default=0.10434782608695652, max_length=255),
            preserve_default=False,
        ),
    ]
