# Generated by Django 4.2.7 on 2023-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='published_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=0.0001941953251888991),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('quick_link', 'Quick Link'), ('picture', 'Picture')], default=0.0001941953251888991, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default=1984, max_length=200),
            preserve_default=False,
        ),
    ]
