# Generated by Django 4.2.6 on 2023-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (3, 'Hr'), (4, 'Employee'), (2, 'Manager')], default=4, null=True),
        ),
    ]
