# Generated by Django 4.2.7 on 2023-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='space',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
