# Generated by Django 4.2.4 on 2023-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blogpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
