# Generated by Django 4.2.6 on 2023-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('hr', 'Hr'), ('user', 'User'), ('manager', 'Manager')], default='user', null=True),
        ),
    ]
