# Generated by Django 4.2.7 on 2023-12-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='space',
        ),
    ]
