# Generated by Django 4.2.6 on 2023-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('manager', 'Manager'), ('user', 'User')], default='user', null=True),
        ),
    ]
