# Generated by Django 4.2.4 on 2023-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.AddField(
            model_name='record',
            name='external_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='record',
            name='internal_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='record',
            name='numbers',
            field=models.JSONField(default=list),
        ),
    ]
