# Generated by Django 4.2.6 on 2023-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('user', 'User')], default='user', max_length=20, null=True),
        ),
    ]
