# Generated by Django 4.2.4 on 2023-10-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_record_description_record_external_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='numbers',
        ),
    ]
