# Generated by Django 4.2.4 on 2023-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_record_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='external_links',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='internal_links',
            field=models.CharField(max_length=255),
        ),
    ]
