# Generated by Django 4.2.4 on 2023-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_record_external_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
