# Generated by Django 4.2.7 on 2023-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='order',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
